name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    container: ghcr.io/mygento/deployer:v5
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Setup APT
        run: sh apt.sh
        env:
          SW_PAT: ${{ secrets.SW_PAT }}
      - name: Check Version
        run: sh check-version.sh
      - name: Results
        run: ls -lah .
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: '*.deb'
      # - name: Upload
      #   if: startsWith(github.ref, 'refs/tags/') != true
      #   run: sh upload.sh
      #   env:
      #     SERVICE: ${{ secrets.SERVICE }}
      #     REALM: ${{ secrets.REALM }}
      #     REALM_LOGIN: ${{ secrets.REALM_LOGIN }}
      #     REALM_PASS: ${{ secrets.REALM_PASS }}
